### PR TITLE
add support for mutiple commands in mqtt message

### PR DESCRIPTION
**Pull request by mhdawson**
harmony-api is a great project.  I use mqtt to glue together a lot
of different home automation pieces and it let me quickly add the
ability to connect/issue commands to my tv setup.

I'm current working on Amazon Alexa control for some additional
features (set channel, volume up/down, mute etc.) that don't 
seem to be built in with the existing logitech/alexa integration.  The 
project is https://github.com/mhdawson/AlexaMqttBridge (still a work in 
progress so no README.md etc. yet).

Along similar lines to the existing support to be able repeat a command
multiple times, this adds the ability to specify multiple commands in a
single mqtt message. This allows me to create a single mqtt message
from Alexa that changes the TV to a particular channel. For example, by
posting "1 7" on the appropriate mqtt topic the commands for 1 and
7 are sent, changing the channel to 17.  

It looks like there are no spaces in the slugs (at least for my devices)
so using spaces to separate the commands seemed safe.  If you 
think there is a better choice, just let me know and I'll update it.

### CODE REVIEW

**Comment by mhdawson** [comment]
bump

**Comment by mhdawson** [comment]
@maddox just wondering if you've had a chance to take a look at this ?

**Comment by mhdawson** [comment]
@maddox still around ?

**Comment by maddox** [comment]
👋 

In order to merge this, it'll need to have the same sort of support for the HTTP api as well. It'll need to be documented in the README too.

Thanks!

**Comment by mhdawson** [comment]
Sorry missed this comment.  Now that I know it is possible to get it in, I'll update to address your suggestions.

**Comment by mhdawson** [comment]
Still on my radar just pretty busy these days.

**Comment by mhdawson** [comment]
I know its been a long time.  Hope to get to this over the holidays

**Comment by mhdawson** [comment]
I guess I'm not going to get to this as its been a long time, closing.

**Pull request closed without merging**
