### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by jawilson**
I use Docker for all of my Home Assistant related things. This makes it easy to start the harmony-api project with a Docker container. You may consider setting up your own Docker repo to replace mine. That way it will update any time you push changes.

### CODE REVIEW

**Comment by maddox** [comment]
I just merged #15. Could you rework this pull based on the mqtt changes already on master? You submitted a pull with all your mqtt changes on this one as well.

Get that in and I'll merge this.

Oh also, I created a docker repo here: https://hub.docker.com/r/jonmaddox/harmony-api/

Thanks!

**Comment by jawilson** [comment]
Done! You once you merge you can update the README to refer to your Docker repo and update your Docker repo to build your GitHube repo.

**Comment by philhawthorne** [comment]
Having issues using Docker on this. Getting repository not found when following the instructions, and when doing `docker pull jonmaddox/harmony-api`

**Comment by jawilson** [comment]
@philhawthorne Looks like @maddox still hasn't linked his Docker repo to the GH repo and hasn't pushed any images to it. Mine should work though, just use `jawilson/harmony-api` e.g.:

```
docker run --name="harmony-api" -v /path/to/your/config:/config \
    -p 8282:8282 -d jawilson/harmony-api
```

**Comment by philhawthorne** [comment]
Thanks @jawilson 

Unfortunately that doesn't seem to work for me either. 

```
 docker run --name="harmony-api-mqtt" -v /volume1/systems/apps/harmony-
mqtt:/config -p 8282:8282 -d jawilson/harmony-api
Unable to find image 'jawilson/harmony-api:latest' locally
latest: Pulling from jawilson/harmony-api
f27b33609fa2: Download complete
e71be54c45c8: Download complete
51c1cff90eba: Download complete
127a1ee4f050: Download complete
0f768761aad8: Download complete
80a2f6a4c72c: Downloading 7.962 MB/9.516 MB
80a2f6a4c72c: Download complete
f80dbf586d37: Download complete
f7eff5f830a7: Download complete
8489b00ba897: Download complete
73896ccf428e: Already exists
1156dc4bc2c3: Already exists
5d979b9859b7: Already exists
06e4c4db013b: Already exists
af5672338792: Already exists
3b47d97fc7b1: Already exists
7f120a132294: Already exists
488b28e08cb6: Already exists
Pulling repository jawilson/harmony-api
FATA[0036] Repository not found

```

**Comment by maddox** [comment]
I linked my account and set up the service hook, but my pushes never show up on Docker :/

**Comment by jawilson** [comment]
@philhawthorne looks like you must have a config wrong or something, all of those images don't match up. I loaded up a clean Ubuntu image and tested without a problem.

```
ubuntu@ubuntu-xenial:~$ sudo docker run --name="harmony-api-mqtt" -p 8282:8282 -d jawilson/harmony-api
Unable to find image 'jawilson/harmony-api:latest' locally
latest: Pulling from jawilson/harmony-api
357ea8c3d80b: Pull complete
52befadefd24: Pull complete
3c0732d5313c: Pull complete
855820c72656: Pull complete
c4c405806e0a: Pull complete
e453523465cd: Pull complete
aef51d7ce00c: Pull complete
6fa03eaf0337: Pull complete
22307318a892: Pull complete
bd302fbad914: Pull complete
Digest: sha256:38c2779d09d463589aba23a031f1de7ef7d7d63f3ff051ff00e1a43e9bf18060
Status: Downloaded newer image for jawilson/harmony-api:latest
a3318574e2f5902e137302a990f909414a387d0fc5640b6f99574a505d0ccc20
```

If you continue to have issues with _my_ image, please post a [new issue on my repo](https://github.com/jawilson/harmony-api/issues/new). If you have issue's with @maddox's repo/image, please post a [new issue to his repo](https://github.com/maddox/harmony-api/issues/new).

**Comment by philhawthorne** [comment]
Thanks @jawilson 

After starting and stopping my docker service, I now have the image up using your Docker URL. Cheers

**Pull request merged**
