### PR TITLE
Manually specify hubs

### PR DESCRIPTION
**Pull request by jawilson**
The changes for multiple hubs removed the ability to manually specify hubs. This adds it back in.

### CODE REVIEW

**Comment by maddox** [comment]
Ha, I silently dropped support for that because I didn't think I had ever documented it.

I originally added it because I had troubles with disconnections when using the discovery method. 
Previously, I was stopping discovery once a hub was found. I was also not handling hubs going away very well. There was also a crasher in one of the internal libraries I am using.

With 2.0, I've solved a couple of issues. The first is a crash that happens on one of the internal libraries. The second is I handle disappearing hubs and I don't stop discovery. This way when a hub goes away, it is cleanly removed from the system, and when it comes back, it is cleanly added back.

The problem is, hardcoding has the exact same problems that existed before these fixes. Without the ability to re-discover, if the connection is lost, it's lost forever until you restart Harmony API. So I honestly don't think we can actually hard code them like this.

Please try your branch for a while and see how it does. I think you might see what happens if the connection is lost. You can force this by power cycling your hub. Also, please try 2.0 as it is now and see if you find any good reason to really need to hard code the IP of your hub.

Most likely though, I will not merge this branch because the discovery functionality is pretty rock solid now.

Thanks!

**Comment by jawilson** [comment]
Unfortunately, discovery doesn't work from within a Docker container without using host networking, which is a problem for me. You certainly don't have to merge these changes into your own branch, but I'll definitely keep them in my fork (yay open source!).

I'll see what I can do about the issues you point out and will hopefully be able to revise this PR to your liking.

**Comment by maddox** [comment]
That's a great point. And a solid argument.

Run this thing locally yourself for a while. See if it's dropping connections and not recovering. We may be able to support it by immediately attempting to reconnect after a disconnect happens. I think that, even if you manually connect, the `away` event may still happen for it.

**Comment by finish06** [comment]
I am in the same boat as jawilson... in docker container... need to manually point to instances.

**Comment by jawilson** [comment]
I've never had a problem with disconnects myself. But I'm going to try to improve this branch based on was @maddox mentioned with manually resetting the hub.

**Comment by finish06** [comment]
Could always set up docker container as network=host... that would allow for scanning I think...  Just an FYI.

**Comment by jawilson** [comment]
As noted in my first response, host networking isn't an option for my specific use.

**Comment by pogil** [comment]
@jawilson I'll be testing this out for a while too. I'm running Ubuntu on Windows 10. I'll keep an eye out whether I drop connections. Have you seen any issues with dropped connections?

**Comment by jawilson** [comment]
I've dropped this project in favor of the built-in Harmony support in HomeAssistant, closing.

**Comment by maddox** [comment]
@jawilson how's it working? I haven't tried it yet. But less software is always better software!

**Comment by jawilson** [comment]
It's working just as well for me as `harmony-api`, tried it out when it first came out and haven't really looked back. It serves all of my specific needs. I was really happy to have this as a stop-gap for support though, thanks for all your hard work.

**Comment by maddox** [comment]
Thanks! No feelings hurt here. Nothing I love more than my software becoming obsolete. Unless I'm making money on it!!

How's the latency? I assume it polls? Can you set it like normal components? I have some decent automations for things firing when my TV turns off. And with harmony-api using MQTT it means it's mostly immediate (if HA was the one doing the off command). Have you found it to be the same?

Also, have you ever noticed increased lag in just using your Harmony remote? Mine has gotten so bad and it's irregular, i've been worrying it's harmony-api sort of DDOSing it or something :/

**Comment by jawilson** [comment]
I certainly haven't had the delay issue. HA does poll, the config is [here](https://home-assistant.io/components/remote.harmony/). There does seem to be a bit of lag time when turning things off, but not enough to bother me.

**Comment by NeoMatrixJR** [comment]
@maddox - Did the manual IP Configuration ever get merged in?  Setting host on my docker isn't working.  It never finds it.

**Pull request closed without merging**
