### PR TITLE
Make current_activity commands to be hub commands. And make them queryable.

### PR DESCRIPTION
**Pull request by farooqu**
I think it make sense to POST to /hubs/:hubSlug/commands/:commandSlug rather than to POST to /hubs/:hubSlug/current_activity/:commandSlug.

Also I think these current activity commands should be queryable.

### CODE REVIEW

**Comment by maddox** [comment]
> Also I think these current activity commands should be queryable.

The commands are currently query-able with:

    GET /hubs/:hub_slug/activities/:activity_slug/commands

I think this is the better approach since it means you can see the commands for each activity ahead of time, rather than having to actually change your activity to get a list of the supported commands.

**Comment by farooqu** [comment]
I agree they are available ahead of time, and that is useful. However, I think it makes sense to be able to see what commands are currently available, rather than having to look up the current activity, and then querying for the commands for that activity, which is why I left that old query in.

**Comment by maddox** [comment]
meh, it seems to me that any time you're going to need to know what the list of commands are, its because you're automating in a specific way. You'll know which activity you're automating for.

I'm not a big fan of being able to do the same thing in 2 ways. This will muddy things up and just add yet anotherrrr endpoint.

**Comment by farooqu** [comment]
I get where you're coming from. And I'm hoping that pulling the common code out might alleviate some of those concerns.

I would still contend though that it is useful to list commands that you have access to, rather than having to look up what your current activity is, and determining what commands that activity has, and then issuing the command on the "current_activity" URI. Feels more "REST"y to GET /hub/:hubSlug/commands, and then to post to /hub/:hubSlug/commands/:commandSlug.

**Comment by maddox** [comment]
> Feels more "REST"y

I agree with this regarding `/hub/:hubSlug/commands/:commandSlug `

**Comment by farooqu** [comment]
Which is more reason to have GET /hub/:hubSlug/commands return the list of commands you can POST to /hub/:hubSlug/commands/:slugCommand. While yes it adds another end-point, I would argue that the GET /hub/:hubSlug/activities/:activitySlug/commands endpoint is the additional and redundant one (albeit nice to have so we have some idea in advance what the commands for different activities are), since there is no corresponding POST for it.

**Comment by maddox** [comment]
OK FINE! Sold me!

**Comment by maddox** [comment]
Welp, I merged it and immediately saw an issue:

Should we change this MQTT topic;

    harmony-api/hubs/family-room/current_activity/command

to

    harmony-api/hubs/family-room/command

to mirror the http api?

**Comment by farooqu** [comment]
Yes we probably should. I can do that and update the docs.

**Comment by farooqu** [comment]
Created pull request #45

**Pull request merged**
